### PR TITLE
add shift functionality for !INCLUDE directives.

### PR DESCRIPTION
**Pull request by Leockard**
Addresses [#15](https://github.com/jreese/markdown-pp/issues/15). Passes all tests in the proposed [test](https://github.com/jreese/markdown-pp/pull/25) suite.

### CODE REVIEW

**Comment by jreese** [comment]
Two things:

1. Please make sure  the readme is updated to cover the new functionality
2. I know it's more difficult, but Markdown also supports underlining headings with `---` or `===`, and it would be great to support that as well, even if it meant blanket replacing the underlines with `##` style headers.

**Comment by Leockard** [comment]
TODO: add a test as soon as test branch is merged.

**Comment by Leockard** [comment]
@jreese just realized the latest python on travis is 3.4. Time to add 3.5?

**Comment by jreese** [comment]
Looks great!  And yes, let's add 3.5 to the build list.  Care to submit a PR for that?

**Pull request merged**
